apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2021-05-23T13:59:31Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "46"
    selfLink: /api/v1/namespaces/default/services/kubernetes
    uid: 1fee76c5-52db-4373-858e-6f784842cd8b
  spec:
    clusterIP: 10.0.0.1
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2021-05-23T14:15:06Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: nginx
    name: my-service
    namespace: default
    resourceVersion: "2375"
    selfLink: /api/v1/namespaces/default/services/my-service
    uid: 4d7a6f8c-fe61-47f9-86e0-aba07f28f99f
  spec:
    clusterIP: 10.0.147.181
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 31733
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: nginx
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 51.136.122.44
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
